# Generated by Django 5.2.6 on 2026-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Empleado', 'Digitador'), ('Privilegiado', 'Supervisor'), ('Admin', 'Admin del sistema')], default='Empleado', max_length=20),
        ),
    ]
