# Generated by Django 6.0 on 2026-01-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appR', '0002_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada')], default='Pendiente', max_length=20),
        ),
    ]
